name: Django CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:7
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping || exit 1"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 20

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run migrations & tests
        env:
          SECRET_KEY: testsecret
          DEBUG: false
          ALLOWED_HOSTS: 127.0.0.1,localhost
          TIME_ZONE: Asia/Kolkata
          EMAIL_HOST_USER: test@test.com
          EMAIL_HOST_PASSWORD: fakepass
          REDIS_HOST: 127.0.0.1
          REDIS_PORT: 6379
          REDIS_DB: 0
        run: |
          python manage.py migrate --noinput
          python manage.py test -v 2
